### PR TITLE
milestone-1

### PR DESCRIPTION
**Pull request by anmolsingh0005**
add schema and ERD screenshot

[Recorded Video ERD And Schema](https://www.loom.com/share/88542b6d020e4021a12391cb558d8eff?sid=8e8f0fa1-5877-4b60-9eec-b1f2a88eca20)

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Update the design, as discussed.

**Comment by anmolsingh0005** [comment]
changed the schema and erd

[Recorded Loom Video](https://www.loom.com/share/7640f22d118646b58300ebff9289b961?sid=79f8b852-6bb7-4b7c-b0e0-4a2c0644c0a1)

**Comment by anmolsingh0005** [comment]
Changed the schema

[Recorded Loom Video](https://www.loom.com/share/7640f22d118646b58300ebff9289b961?sid=b55099fc-bf63-48f7-b42e-25d412eecb10)

**Comment by PRASANNAPATHI** [comment]
Yes Anmol, It looks fine now.

Please, merge it now.

**Pull request merged**
